# Run install and unit tests against supported Python versions on each PR to master.

name: Test Against Pythons

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12", "3.13"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Principal Mapper
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install .
          pip show principalmapper

      - name: Run test cases
        shell: bash
        run: python -m unittest discover -s tests -p "test*.py" -v
